open-mmlab/mmrotate

mmrotate/core/visualization/image.py
mmrotate/models/detectors/base.py

Fix #9 
Fix the visualization bugs brought by the new feature in https://github.com/open-mmlab/mmdetection/pull/6716.
If this PR introduces a new feature, it is better to list some use cases here, and update the …

[Fix] fix visualization bugs

---

docs/en/get_started.md
docs/zh_cn/get_started.md

[Fix] fix bug in docs/get_started.md

---

requirements/runtime.txt

fix the issue #6 
I was modified the `requirements/runtime.txt`, change the `mmcv` to `mmcv-full`, can fix this problem. 
If this PR introduces a new feature, it is better to list some use cases here, and update the …

[Fix] fix install an additional mmcv. #6

---

.pre-commit-config.yaml

Add checking copyright pre-commit hook in mmrotate.
1. Pre-commit or other linting tools are used to fix the …

[Fix] Add checking copyright pre-commit hook

---

.github/workflows/build.yml

Add CI for windows

---

docs/en/faq.md
docs/zh_cn/faq.md

Update the faq.md.
Add content about e2cnn in faq.md.
2. The modification is covered by complete …

[Docs] Update the faq.md about e2cnn.

---

.github/workflows/build.yml

Delete -sv in CI

---

mmrotate/datasets/dota.py

Debug for #45 
Instead of directly initializing `Pool()` for multi-thread processing, initializing through `get_context("spawn")`.
None
Debugging for issue #45

[Debug] for issue #45

---

README.md
README_zh-CN.md

Update Projects in OpenMMLab.
2. The …

Update Projects in OpenMMLab.

---

mmrotate/core/visualization/image.py

Fix label bug in visualization.
2. …

Fix label bug in visualization.

---

docs/en/faq.md
docs/zh_cn/faq.md

Update links in faq.md.
2. The …

Update links in faq.md

---

docs/en/get_started.md
docs/zh_cn/get_started.md
tools/dist_test.sh
tools/dist_train.sh

Add multi machine dist_train.
2. The …

[Feature] Add multi machine dist_train

---

tools/train.py

Add diff seeds to diff ranks. Refer to https://github.com/open-mmlab/mmselfsup/pull/228/files …

[Feature] Add diff seeds to diff ranks 

---

.dev_scripts/gather_models.py
.dev_scripts/gather_models.py 
setup.cfg

Add  `.dev_scripts/gather_models.py` for batch processing and publishing model.
1. Pre-commit or other linting tools …

Add  .dev_scripts/gather_models.py

---

mmrotate/datasets/hrsc.py

resolve #173 
2. The modification is …

Fix bug in HRSCDataset with clasesswise=ture

---

docs/en/index.rst
docs/en/useful_tools.md
docs/zh_cn/index.rst
docs/zh_cn/useful_tools.md
mmrotate/models/detectors/oriented_rcnn.py
mmrotate/models/roi_heads/gv_ratio_roi_head.py
mmrotate/models/roi_heads/oriented_standard_roi_head.py
mmrotate/models/roi_heads/roi_trans_roi_head.py
tools/analysis_tools/confusion_matrix.py
tools/analysis_tools/get_flops.py

Issue #145 
add `get_flops` from https://github.com/open-mmlab/mmdetection/blob/master/tools/analysis_tools/get_flops.py
Add `docs/en/useful_tools.md`
Add `tools/analysis_tools/get_flops.py`
Add forward_dummy for `oriented_rcnn` and `oriented_standard_roi_head`
S2ANet still has some issues with flops, because mmcv doesn't support dcn and orconv flops.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure …

[Feature] Support get flops tool

---

mmrotate/models/roi_heads/roi_extractors/rotate_single_level_roi_extractor.py

Resolve #167 
2. The modification is …

[Fix] 'RoIAlignRotated' object has no attribute 'output_size'

---

README.md
README_zh-CN.md

Update citation of mmrotate in README.md

---

mmrotate/models/dense_heads/oriented_rpn_head.py
mmrotate/models/dense_heads/rotated_rpn_head.py

Fix a bug in Rotated FasterRCNN-OBB.
Change the rotated_anchor_inside_flags in the _get_targets_single function to anchor_inside_flags implemented in MMDetection.
1. Pre-commit …

[Fix]  Modify the use of rotated anchor inside flags

---

.github/workflows/build.yml
docker/Dockerfile

[Fix] Fix GPG key error in CI and docker

---

mmrotate/apis/inference.py
mmrotate/core/patch/merge_results.py

solve #276.
Support mask in `merge_results`.
Support instance segmantation models in huge_image_demo.py
1. …

[Enhance] Support mask in merge_results and huge_image_demo.py.

---

docs/zh_cn/conf.py

[Docs] Configure Myst-parser to parse anchor tag for zh_CN doc.

---

.github/workflows/build.yml

[Fix] Fix windows CI.

---

mmrotate/datasets/dota.py
mmrotate/datasets/hrsc.py
tests/test_data/test_datasets/test_dota.py

[Feature] Allow turn-off filter_empty_gt

---

configs/_base_/datasets/dotav1.py
configs/_base_/datasets/hrsid.py
configs/_base_/datasets/ssdd.py
configs/kfiou/r3det_kfiou_ln_swin_tiny_adamw_fpn_1x_dota_ms_rr_oc.py
configs/kfiou/roi_trans_kfiou_ln_r50_fpn_1x_dota_ms_rr_le90.py
configs/kfiou/roi_trans_kfiou_ln_swin_tiny_fpn_1x_dota_ms_rr_le90.py
configs/roi_trans/roi_trans_r50_fpn_1x_dota_ms_le90.py
configs/rotated_retinanet/rotated_retinanet_obb_r50_fpn_1x_dota_ms_rr_le90.py

Fix path error in cfg

---

mmrotate/datasets/pipelines/transforms.py

Fix bugs in PolyRandomRotate if auto_bound is True.
`np.cos` needs radians and original codes lead to miscalculation of final image sizes.
If this PR introduces a new feature, it is better to list some use cases here, and …

fix bugs in PolyRandomRotate

---

configs/_base_/schedules/schedule_1x.py
configs/_base_/schedules/schedule_3x.py
configs/_base_/schedules/schedule_40e.py
configs/_base_/schedules/schedule_6x.py

Update checkpoint and eval Interval

---

requirements/docs.txt

[Please describe the motivation of this PR and the goal you want to achieve through this PR.](https://readthedocs.org/projects/mmcv/builds/17455215/
Failed to build docs due to breaking changes of markdown3.4. More details at ryanfox/sphinx-markdown-tables#36.)https://readthedocs.org/projects/mmcv/builds/17455215/
Failed to build docs due to breaking changes of markdown3.4. More details at https://github.com/ryanfox/sphinx-markdown-tables/issues/36.
Fix the markdown version.
Does the modification introduce changes that break the …

Fix markdown version

---

configs/redet/redet_re50_refpn_1x_dota_le90.py
configs/redet/redet_re50_refpn_fp16_1x_dota_le90.py
configs/roi_trans/roi_trans_r50_fpn_1x_dota_le135.py
configs/roi_trans/roi_trans_r50_fpn_1x_dota_le90.py
configs/roi_trans/roi_trans_r50_fpn_1x_dota_ms_le90.py
configs/roi_trans/roi_trans_r50_fpn_1x_dota_oc.py
configs/roi_trans/roi_trans_r50_fpn_fp16_1x_dota_le90.py
configs/roi_trans/roi_trans_swin_tiny_fpn_1x_dota_le90.py
configs/s2anet/s2anet_r50_fpn_1x_dota_le90.py
configs/s2anet/s2anet_r50_fpn_fp16_1x_dota_le135.py
mmrotate/models/backbones/re_resnet.py
mmrotate/models/necks/re_fpn.py
tests/test_models/test_backbones/test_re_resnet.py
tests/test_models/test_necks/test_re_fpn.py

roi_trans_r50_fpn_1x_dota_le90.py
report AP50: 76.08
AP50: 0.7634093210496002
AP75: 0.533343851852512
mAP: 0.48567697751826194
redet_re50_fpn_1x_dota_le90.py
report AP50: 76.68
AP50: 0.7631660478247589
AP75: 0.5257915868701769
mAP: 0.48583598473547074

Refactor roi trans & redet

---

mmrotate/models/dense_heads/s2a_head.py

Fix channal in s2a_head

---

mmrotate/core/bbox/coder/__init__.py

Fix a bug caused by https://github.com/open-mmlab/mmrotate/pull/520
1. Pre-commit or other linting tools are used to …

Fix core/bbox/coder/__init__.py

---

mmrotate/models/losses/kf_iou_loss.py

Resolve #541
2. The modification is …

Fix kfiou loss nan bug.

---

configs/_base_/default_runtime.py
demo/huge_image_demo.py
demo/image_demo.py
mmrotate/apis/inference.py
mmrotate/visualization/__init__.py
mmrotate/visualization/local_visualizer.py
mmrotate/visualization/palette.py
tests/test_visualization/test_local_visualizer.py
tests/test_visualization/test_palette.py
tools/analysis_tools/browse_dataset.py

Refactor visualizer

---

configs/_base_/datasets/dota_coco.py
mmrotate/datasets/transforms/__init__.py
mmrotate/datasets/transforms/transforms.py
tests/test_datasets/test_transforms/test_transforms.py
tools/data/dota/README.md
tools/data/dota/dota2coco.py

Support Coco style annotations

---

tools/analysis_tools/analyze_logs.py
tools/analysis_tools/confusion_matrix.py
tools/misc/print_config.py
tools/test.py

Refactor tools

---

README.md
README_zh-CN.md
docs/en/migration.md
docs/zh_cn/index.rst
docs/zh_cn/migration.md

Update readme of 1.0.0rc0

---

README.md
README_zh-CN.md
docs/en/migration.md
docs/zh_cn/index.rst
docs/zh_cn/migration.md

* update
* Update README_zh-CN.md
If this PR introduces a new feature, it is better to list some use cases here, and update the …

Update readme of 1.0.0rc0 (#603)

---

.github/workflows/merge_stage_test.yml
.github/workflows/pr_stage_test.yml

Refer to https://github.com/open-mmlab/mmocr/pull/1525

fix windows ci

---

tools/test.py

Fix bug in tools/test.py

---

.pre-commit-config-zh-cn.yaml

Add the domestic source to speed up pre-commit.
Add `.pre-commit-config-zh-cn.yaml`

[Enhance] Add `.pre-commit-config-zh-cn.yaml`

---

docker/Dockerfile

Existing dockerfile is based on mmroate 0.x and I add  a dockerfile for mmrotate 1.x
Modified docker/Dockerfile 
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. The documentation has been modified accordingly, like docstring or example tutorials.

add mmrotate 1.x dockerfile

---

model-index.yml

Delete g_reppoints in metainfo

---

requirements/optional.txt
requirements/tests.txt

```
× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [18 lines of output]
The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
rather than 'sklearn' for pip commands.
```
If so, please describe how it breaks the compatibility and how the downstream …

[Fix][dev-1.x] sklearn depreated, install scikit-learn

---

requirements/optional.txt
requirements/tests.txt

```
× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [18 lines of output]
The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
rather than 'sklearn' for pip commands.
```
If so, please describe how it breaks the compatibility and how the downstream …

[Fix] sklearn depreated, install scikit-learn

---

.gitignore

Add data/ or data in the .gitignore file

[Enhance]: add data gitignore

---

.github/workflows/merge_stage_test.yml
mmrotate/models/necks/re_fpn.py

Fix CI error when 'numpy >= 1.24.0'.

Fix CI error when 'numpy >= 1.24.0'

---

.github/workflows/build.yml
requirements/runtime.txt
requirements/tests.txt

Use the latest e2cnn version to resolve numpy compatibility problem.
Related PR: https://github.com/QUVA-Lab/e2cnn/pull/65
update the requirements files …

upgrade e2cnn version

---

docs/zh_cn/get_started.md

完成了get_started的文档翻译，但是存在三个问题无法独立解决：在“需要准备的依赖环境”一节中，note中的一个链接无法完成链接功能；在“在Google Colab上安装”的第三步中，note中有一个无法完成的链接并且``引用无法正确显示。
应该完全没动其他文件，但是提交未draft之后发现conversation中有提示一些conflicts。
超级视客营初级任务
完成了get_started的文档翻译
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. The documentation has been modified accordingly, like docstring or example tutorials.

get_started 文档翻译

---

.circleci/test.yml

fix circle ci

---

mmrotate/datasets/transforms/transforms.py

[Fix] Fix img_shape in Rotate

---

mmrotate/models/detectors/refine_single_stage.py

Fix import errors in mmyolo

---

README.md
README_zh-CN.md

Add PSC in README.md

---

README.md
README_zh-CN.md
configs/psc/README.md

MMRotate has one model accepted by CVPR2023. Congratulations!
- Phase-Shifting Coder: Predicting Accurate Orientation in Oriented Object Detection

Update CVPR2023 paper

---

README.md
README_zh-CN.md

[doc]:add more social network links
README.md and README_zh-CN.md
2. The modification is covered …

[doc] add social network links

---

mmrotate/apis/train.py
mmrotate/models/dense_heads/rotated_anchor_head.py
mmrotate/utils/__init__.py
mmrotate/utils/util_distribution.py
tools/test.py
tools/train.py

support training mmrotate on NPU
Add NPU adaptation code
2. The modification is covered by …

support training mmrotate on NPU

---

README.md
README_zh-CN.md

update readme of playground project
