mmrotate/datasets/dota.py
fix  bug in #10 
2. The modification …
=> [Fix] fix eval bug when single processing.

mmrotate/datasets/dota.py, mmrotate/models/dense_heads/kfiou_odm_refine_head.py, mmrotate/models/dense_heads/kfiou_rotate_retina_head.py, mmrotate/models/dense_heads/kfiou_rotate_retina_refine_head.py, mmrotate/models/dense_heads/odm_refine_head.py, mmrotate/models/dense_heads/rotated_anchor_head.py, mmrotate/models/dense_heads/rotated_retina_head.py, mmrotate/models/dense_heads/rotated_retina_refine_head.py, mmrotate/models/detectors/r3det.py, mmrotate/models/detectors/rotated_reppoints.py, mmrotate/models/detectors/rotated_retinanet.py, mmrotate/models/detectors/s2anet.py, requirements/build.txt, requirements/runtime.txt
Add init_cfg for dense heads to prevent multiple initialization.
[switch back to orginal pycocotools](https://github.com/open-mmlab/mmdetection/pull/6838), pycocotools-windows didn't support python 3.9.
Add init_cfg for dense heads.
switch back to original pycocotools on Windows
If this …
=> Add init_cfg for dense heads.

docs/zh_cn/model_zoo.md
Add Chinese version of `docs/zh_cn/model_zoo.md`.
Add Chinese version of `docs/zh_cn/model_zoo.md`.
1. Pre-commit or other linting tools are used to fix the potential lint …
=> [Docs] Add Chinese version of model_zoo.md

mmrotate/models/roi_heads/roi_extractors/rotate_single_level_roi_extractor.py
Debug for issue #40 
Since `RiRoIAlignRotated` object does not have attribute `output_size` but `out_size`, and vice versa for other RoI in `mmcv`.
-> Check if object is `RiRoIAlignRotated` then get `out_size` attribute, if not get `output_size` 
This change make code work without changing downstream repo (`mmcv`), however I think better to update downstream `mmcv` repo; specifically in https://github.com/open-mmlab/mmcv/blob/fd3a1a16ea1d0b3def8719816007a5d6fd6b432e/mmcv/ops/riroi_align_rotated.py#L121
=> `self.out_size` to `self.output_size`
If this PR is for debugging #40
=> [DEBUG] Temporary fix for issue "'RoIAlignRotated' object has no attribute 'out_size'" #40

mmrotate/core/bbox/iou_calculators/rotate_iou2d_calculator.py, tests/test_utils/test_overlaps.py
Fix rbbox_overlaps abnormal when the box is too small.
1. Pre-commit or other linting tools are used to fix the …
=> Fix rbbox_overlaps abnormal when the box is too small.

tools/analysis_tools/confusion_matrix.py
1. Add analysis tool to generate confusion matrix adapted from https://github.com/open-mmlab/mmdetection
If this PR introduces a new …
=> Add confusion matrix tools analysis

configs/kfiou/r3det_kfiou_ln_swin_tiny_adamw_fpn_1x_dota_ms_rr_oc.py, configs/kfiou/roi_trans_kfiou_ln_swin_tiny_fpn_1x_dota_le90.py, configs/oriented_rcnn/oriented_rcnn_swin_tiny_fpn_1x_dota_le90.py, configs/roi_trans/roi_trans_swin_tiny_fpn_1x_dota_le90.py
Add URL of Swin pretrained model.
2. …
=> [Fix] Add URL of Swin pretrained model.

mmrotate/models/dense_heads/sam_reppoints_head.py
1.assign函数参数顺序错误，overlaps参数位置错误（这个问题不影响正常训练，是我调试的时候发现的，你们可以确认一下，这个有没响）
2.all_overlaps_rotate_list之前大小固定为4，应该按照一个batchsize大小进行设置，修改之后不会报tensor维度错误，可以正常训练
（修改了lint错误，重新提交一次）
=> [Fix] Bug for SASM durning training.

tools/analysis_tools/benchmark.py
1. add codes for inference speed statistics from https://github.com/open-mmlab/mmdetection
2. fix the bug in eval_map
If this PR introduces a new feature, it is better to list some use cases here, and update the …
=> [Feature] add codes for inference speed statistics

mmrotate/core/visualization/image.py, tools/misc/browse_dataset.py
Fix the bug in imshow_det_rbboxes when input bboxes are without scores. Add browse_dataset for visualization.
1. …
=> Add browse_dataset for visualization

mmrotate/core/evaluation/eval_map.py
Resolve #208 
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. The documentation has been modified accordingly, like docstring or example tutorials.
=> [Fix] bug in eval_rbbox_map when labels_ignore is None

demo/README.md, demo/huge_image_demo.py, demo/image_demo.py, docs/en/api.rst, docs/zh_cn/api.rst, mmrotate/core/visualization/__init__.py, mmrotate/core/visualization/image.py, mmrotate/core/visualization/palette.py, mmrotate/datasets/dota.py, mmrotate/datasets/hrsc.py, mmrotate/datasets/sar.py, mmrotate/models/detectors/base.py, tests/test_utils/test_visualization.py
Follow mmdet https://github.com/open-mmlab/mmdetection/pull/6716
#121 
DOTA palette follow [BboxToolkit](https://github.com/jbwang1997/BboxToolkit/blob/master/tools/vis_configs/dota1_0/colors.txt)
before:
after:
Use matplotlib instead of cv2.
Support visualize boxes of diff classes as diff colors.
Add palette for DOTA dataset
Remove `output` in `image_demo.py`
If so, please describe how it breaks the compatibility and how the …
=> [Enhance] Refactor `imshow_det_rbboxes`

docs/zh_cn/useful_tools.md
Add torchserve doc in zh_cn
Follow [mmcls doc](https://github.com/open-mmlab/mmclassification/blob/master/docs/zh_CN/tools/model_serving.md)
docs/zh_cn/useful_tools.md
1. …
=> Add torchserve doc in zh_cn

docs/en/conf.py
By default, myst-parser did not parse links to anchor tags in markdown files, making these hyperlinks become raw texts in docs. This PR updates myst's configuration to enable this feature.
related PR https://github.com/open-mmlab/mmocr/pull/1012
=> [Docs] Configure Myst-parser to parse anchor tag

mmrotate/datasets/builder.py
For future support of Mosaic and Mixup
1. Pre-commit or other linting tools are used to fix the potential lint …
=> Add MultiImageMixDataset in build_dataset

mmrotate/core/post_processing/bbox_nms_rotated.py
fix max_coordinate in multiclass_nms_rotated
1. Pre-commit or other linting tools are used to fix the potential lint …
=> fix max_coordinate in multiclass_nms_rotated

.github/workflows/test_mim.yml, configs/csl/metafile.yml, model-index.yml
Ref: https://github.com/open-mmlab/mmsegmentation/pull/1654
=> [Enhancement] Test mim in CI

mmrotate/core/bbox/assigners/max_convex_iou_assigner.py, mmrotate/models/dense_heads/rotated_reppoints_head.py
bug fix when negative image training using reppoint head
error when number of gt bbox is zero
1. Added exception handling to `get_pos_loss` function of `RotatedRepPointsHead` class.
2. Added exception handling to `convex_overlaps` function of `MaxConvexIoUAssigner` class.
=> reppoint bug fix when negative image training

tools/misc/browse_dataset.py
ABCs were moved from collections to collections.abc in 3.3. Since 3.10, ABCs cannot be imported directly from collections.
> Please describe the motivation of this PR and the goal you want to achieve through this PR.
The script does not work with Python 3.10. The reason is that the abstract base classes in the `collections` module were moved to  `collections.abc` in Python 3.3. Until 3.9, importing an abstract base class from `collections` produced a deprecation warning, and in 3.10 it produces an error.
> Please briefly describe what modification is made in this PR.
If version < 3.3 import from `collections` else import from `collections.abc`.
=> [Fix] browse_dataset.py not working in python3.10

tools/analysis_tools/confusion_matrix.py
1. Removed invalid `score_threshold` arg  in `nms_rotated` call
2. Passed `--color-theme` to `plot_confusion_matrix`
> Please describe the motivation of this PR and the goal you want to achieve through this PR.
This PR aims to fix a non-working `--color-theme` command line argument and to prevent the script from crashing whenever `--nms-iou-thr` is specified.
> Please briefly describe what modification is made in this PR.
The non-working `--color-theme` argument is now passed to the `plot_confusion_matrix` call.
The `--nms-iou-thr` is fixed by removing an invalid `score_threshold` argument  in an `nms_rotated` call.
=> [Fix] confusion_matrix.py arguments not working / crashing the script.

mmrotate/evaluation/metrics/rotated_coco_metric.py
Import RotatedBoxes from mmrotate.structures.bbox, not mmrotate.core.
=> [FIX] Import RotatedBoxes from structures not core

mmrotate/visualization/local_visualizer.py, tests/test_visualization/test_local_visualizer.py
To handle tensor bboxes in `RotLocalVisualizer`.
reslove #611
1. Pre-commit or other linting tools are used to fix …
=> Fix image_demo bug.

mmrotate/structures/bbox/bbox_overlaps.py, tests/test_models/test_task_modules/test_rotated_iou2d_calculator.py
Fix the output of `rbbox_overlaps` error in some case, which may appear in mmocr.
1. Pre-commit or other linting …
=> Fix rbbox_overlaps error

tools/analysis_tools/get_flops.py
=> [Fix] fix get_flops.py

docs/en/tutorials/customize_dataset.md
explicitly over-write all the `num_classes` field from default 15 to 5.
Here the num_classes should be 5, but it's given 15
If this …
=> Minor correction in the documentation

mmrotate/datasets/pipelines/transforms.py
Previously, valid_rbboxes are determined with their center points.
Following https://github.com/open-mmlab/mmrotate/blob/bc1ced4cafdc8d62305958512b0195d822ff6c7f/tools/data/dota/split/img_split.py#L79, replace it with more appropriate criteria: IoF(Intersection over foreground)
If so, please describe how it breaks the compatibility and how the downstream projects should …
=> [Enhance] use iof for RRandomCrop validation

configs/_base_/datasets/dota_coco.py, configs/_base_/datasets/hrsid.py, configs/_base_/datasets/rsdd.py, configs/_base_/datasets/srsdd.py, configs/_base_/datasets/ssdd.py, mmrotate/datasets/dior.py, mmrotate/datasets/dota.py, mmrotate/datasets/hrsc.py, mmrotate/visualization/palette.py, tests/test_datasets/test_dior.py, tests/test_datasets/test_hrsc.py, tests/test_visualization/test_palette.py, tools/analysis_tools/confusion_matrix.py
Modify keys in dataset.metainfo to lower case. 
`CLASSES`  -> `classes`
`PLATTE` -> `platte` …
=> Modify keys in dataset.metainfo to lower case.

mmrotate/evaluation/functional/mean_ap.py, mmrotate/testing/_utils.py, mmrotate/utils/patch/merge_results.py, mmrotate/visualization/local_visualizer.py, tools/analysis_tools/browse_dataset.py
Deprecating old type alias due to new version of numpy.
1. Replace the `np.int` with `np.int32`.
2. Replace all `np.bool` with `bool`.
=> [Fix] Deprecating old type alias due to new version of numpy

requirements/build.txt
Due to e2cnn compatibility issues, limit numpy<1.24.0
=> limit numpy version

mmrotate/core/evaluation/eval_map.py, mmrotate/core/patch/merge_results.py
`np.bool` is deprecated which was alias for python `bool`.
Replace `np.bool` with `bool`.
Please check
- https://github.com/open-mmlab/mmdetection/pull/9537
- https://github.com/QUVA-Lab/e2cnn/pull/65
=> [Fix] Fix deprecated `np.bool`

mmrotate/datasets/pipelines/transforms.py
Sometimes it is useful to use **negative patches** in the training phase as in https://github.com/open-mmlab/mmdetection/blob/1b7d778da310eccff95bb8e401f5845a03b17ba9/configs/common/lsj_100e_coco_instance.py#L32.
Currently, however, `PolyRandomRotate` does not support negative patches.
Add an option to allow negative patches in the `PolyRandomRotate`.
=> [Feature] Support negative patches in PolyRandomRotate

tools/test.py
After introducing `setup_multi_processes` in `tools.test.py`, `dataset.format_results(output, **kwargs)` becomes seriously slow because it silently handles the error when merging results.
The error message is `RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method`, which is not related to GPU OOM.
When formatting the result, change `mp_start_method` to `spawn` following https://github.com/pytorch/pytorch/issues/40403#issue-643410598.
=> [Fix] Fix using multiprocessing when formatting

README.md, README_zh-CN.md, configs/h2rbox/README.md, configs/kfiou/README.md
MMRotate has two models accepted by ICLR2023. Congratulations!
- H2RBox: Horizontal Box Annotation is All You Need for Oriented Object Detection
- The KFIoU Loss for Rotated Object Detection
=> Update ICLR2023 papers

.circleci/test.yml, .github/workflows/merge_stage_test.yml, configs/redet/README.md, mmrotate/models/backbones/re_resnet.py, mmrotate/models/necks/re_fpn.py, mmrotate/models/utils/__init__.py, mmrotate/models/utils/enn.py, requirements/build.txt, requirements/runtime.txt, requirements/tests.txt, tests/test_models/test_backbones/test_re_resnet.py, tests/test_models/test_necks/test_re_fpn.py
https://github.com/open-mmlab/mmyolo/pull/513
- Only ReDet use `e2cnn`, so we set it as an optional dependency. 
- Unlimit numpy version.
If this PR introduces a new feature, it is better to list some use cases here, and …
=> Set `e2cnn` as an optional dependency

configs/_base_/datasets/dota.py, configs/_base_/datasets/dota_ms.py, configs/_base_/datasets/dota_qbox.py, configs/_base_/datasets/dotav15.py, configs/_base_/datasets/dotav2.py, configs/rotated_rtmdet/_base_/dota_rr.py, configs/rotated_rtmdet/_base_/dota_rr_ms.py, mmrotate/datasets/dota.py
=> Update DOTA dataset for mmyolo

configs/_base_/datasets/hrsid.py
close #759 
2. The modification is …
=> Fix loss NaN bug when training HRSID dataset.

mmrotate/models/task_modules/assigners/convex_assigner.py
fix runtime error in https://github.com/open-mmlab/mmrotate/blob/1.x/mmrotate/models/task_modules/assigners/convex_assigner.py#L142
mmrotate/models/task_modules/assigners/convex_assigner.py#L136
```diff
class ConvexAssigner(BaseAssigner):
assigned_gt_inds = points.new_zeros((num_points, ), dtype=torch.long)
assigned_gt_dist = points.new_full((num_points, ), float('inf'))
-        points_range = torch.arange(points.shape[0])
+        points_range = torch.arange(points.shape[0], device=points.device)
for idx in range(num_gts): …
```
=> [Fix] Move points_range to the same device with points

mmrotate/structures/bbox/bbox_overlaps.py
Fix bug when training images without gt.
1. Pre-commit or other linting tools are used to fix the potential lint …
=> Fix bug when training images without gt.

projects/LSKNet/lsknet/lsknet.py
Use mmengine for openmmlab 2.0
2. …
=> [Fix] fix LSKNet error in import

docs/zh_cn/tutorials/customize_dataset.md
The zh_cn doc is inconsistent with the en version:
https://github.com/open-mmlab/mmrotate/blob/04405ab0f0f0c580cc909df15a162de65a9b668a/docs/en/tutorials/customize_dataset.md?plain=1#L37-L38
=> [Docs] Fix wrong zh_cn doc in customize_dataset.md

tools/train.py
Migrate from mmdet
https://github.com/open-mmlab/mmdetection/blob/ecac3a77becc63f23d9f6980b2a36f86acd00a8a/tools/train.py#L51-L54
=> [Fix] Update train.py to support distributed training with PyTorch>= 2.0.0

mmrotate/core/post_processing/bbox_nms_rotated.py
When I validated the installation according to the document [[Verify the inference demo]](https://mmrotate.readthedocs.io/en/latest/install.html#installation:~:text=Step%202.%20Verify,run%20the%20following%20command.), I found that using `demo/image_demo.py` script would result in the following error.
```shell
Traceback (most recent call last):
File "demo/image_demo.py", line 45, in <module>
main(args)
File "demo/image_demo.py", line 32, in main
result = inference_detector(model, args.img)
File "/home/cvrsg/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/apis/inference.py", line 157, in inference_detector
results = model(return_loss=False, rescale=True, **data)
File "/home/cvrsg/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in …
```
=> [Fix] fix bbox_nms_rotated label device

mmrotate/models/dense_heads/h2rbox_head.py
I tried to run h2rbox with sar ship data set, such as rsdd. But an AssertError raise as:
```
File "/mnt/petrelfs/liqingyun/miniconda3/envs/mm2/lib/python3.8/site-packages/mmrotate/models/dense_heads/h2rbox_head.py", line 706, in _predict_by_feat_single
results.bboxes = RotatedBoxes(bboxes)
File "/mnt/petrelfs/liqingyun/miniconda3/envs/mm2/lib/python3.8/site-packages/mmengine/structures/instance_data.py", line 152, in __setattr__
assert len(value) == len(self), 'The length of ' \
AssertionError: The length of values 30 is not consistent with the length of this :obj:`InstanceData` 1
```
Here is my config:
```python
"""
NOTE: Steps
1. change dataset-related configs, such as dataloader, evaluator.
2. change size-related item in model and new pipeline configs. (You may require to define a new …
```
=> [Fix] box error in h2rbox_head.py

mmrotate/datasets/dota.py
I would like to use the OrientedRCNN model, but it seems that the model library in version 1.x is not yet fully developed. Therefore, I choose to continue using the main version. In the main version, when testing with the DOTA dataset, I encounter the following error due to array out-of-bounds:
```python
Merging patch bboxes into the full image!!!
Traceback (most recent call last):
File "/my/path/to/mmrotate/tools/test.py", line 271, in <module>
main()
File "/my/path/to/mmrotate/tools/test.py", line 253, in main
dataset.format_results(outputs, **kwargs)
File "/my/path/to/mmrotate/mmrotate/datasets/dota.py", line 327, in format_results
id_list, dets_list = self.merge_det(results, nproc)
File "/my/path/to/mmrotate/mmrotate/datasets/dota.py", line 230, in merge_det
x_y_2 = re.findall(r'\d+', …
```
=> [Fix] Fix potential array overrun risk

mmrotate/models/losses/rotated_iou_loss.py
Fix #888
After this fix, the loss is normal
```
06/26 10:28:07 - mmengine - INFO - Epoch(train)   [1][  50/1000]  lr: 6.1323e-06  eta: 1 day, 2:56:08  time: 0.9702  data_time: 0.1629  memory: 30334  loss: 2.0993  loss_cls: 0.8395  loss_bbox: 1.2598
06/26 10:28:45 - mmengine - INFO - Epoch(train)   [1][ 100/1000]  lr: 1.2389e-05  eta: 1 day, 0:03:42  time: 0.7640  data_time: 0.0112  memory: 29992  loss: 1.9670  loss_cls: 0.7536  loss_bbox: 1.2134
06/26 10:29:24 - mmengine - INFO - Epoch(train)   [1][ 150/1000]  lr: 1.8645e-05  eta: 23:06:32  time: 0.7654  data_time: 0.0124  memory: 30087  loss: 1.9570  loss_cls: 0.7950  loss_bbox: 1.1620
06/26 10:30:05 - mmengine - INFO - Epoch(train)   [1][ 200/1000]  lr: 2.4901e-05  eta: 23:07:00  time: 0.8360  data_time: 0.0772  memory: 30005  loss: …
```
=> [Fix] Fix nan loss in RotatedIoULoss when using AmpOptimizer
